name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install Dependency
        run: pnpm install --no-frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run pnpm ci
        run: pnpm run ci

      - name: Run http server and test
        run: |
          pnpm http-server .next -p 3000 &

      - name: Run playwright test
        run: pnpm run test

      - name: Stop http server
        run: |
          pkill -15 "http-server"

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
